Repository st0012/object_tracer, pull requests merged in 2020-06, with the labels that each got.

#39 Fix typo: Guadian -> Guardian
  README.md
Labels: documentation

#40 Update GitHub Actions Configuration
  .github/workflows/ruby.yml
Labels: CI Issues

#42 Refactorings
  lib/tapping_device.rb
  lib/tapping_device/exceptions.rb
  lib/tapping_device/trackable.rb
  lib/tapping_device/trackers/association_call_tracker.rb
  lib/tapping_device/trackers/initialization_tracker.rb
  lib/tapping_device/trackers/method_call_tracker.rb
  lib/tapping_device/trackers/passed_tracker.rb
  spec/methods/tap_assoc_spec.rb
  spec/methods/tap_init_spec.rb
  spec/output_payload_spec.rb
  spec/payload_spec.rb
  spec/performance_spec.rb
  spec/tapping_device_spec.rb
Labels: Refactoring

#45 Hijack attr methods with `hijack_attr_methods` option
  .DS_Store
  README.md
  lib/tapping_device.rb
  lib/tapping_device/method_hijacker.rb
  lib/tapping_device/trackers/mutation_tracker.rb
  spec/methods/tap_on_spec.rb
Labels: Feature

#47 Support write_* helpers
  README.md
  lib/tapping_device.rb
  lib/tapping_device/output.rb
  lib/tapping_device/output/file_writer.rb
  lib/tapping_device/output/payload.rb
  lib/tapping_device/output/stdout_writer.rb
  lib/tapping_device/output/writer.rb
  lib/tapping_device/output_payload.rb
  lib/tapping_device/trackable.rb
  lib/tapping_device/trackers/mutation_tracker.rb
  spec/matchers/write_to_file_matcher.rb
  spec/output_payload_spec.rb
  spec/spec_helper.rb
  spec/trackable/output_helpers_spec.rb
  spec/trackable/tap_helpers_spec.rb
Labels: Feature

#48 Support Global Configuration
  CHANGELOG.md
  README.md
  lib/tapping_device.rb
  lib/tapping_device/configurable.rb
  lib/tapping_device/output.rb
  lib/tapping_device/output/file_writer.rb
  lib/tapping_device/trackable.rb
  spec/configurable_spec.rb
  spec/trackable/output_helpers_spec.rb
Labels: Feature

#53 Fix tap_init by adding c_* event type
  lib/tapping_device.rb
  lib/tapping_device/trackers/initialization_tracker.rb
  spec/methods/tap_init_spec.rb
Labels: Bug fix

#55 Add force_recording option for debugging
  lib/tapping_device.rb
  spec/shared_examples/optionable_examples.rb
Labels: Feature

#56 Add with_* helpers (e.g. with_print_calls)
  README.md
  lib/tapping_device/trackable.rb
  spec/trackable/output_helpers_spec.rb
Labels: Feature
